import keyMirror from 'key-mirror'

export default keyMirror({
  LOADED_TOPICS: null,
  LOADED_POSTS: null,

  GET_OVERLAY_MODELS: null,
  PUSH_OVERLAY_MODEL: null,
  POP_OVERLAY_MODEL: null,

  SET_PLATFORM: null,
  SET_VERSION: null,

  LOGIN_VIA_SOCIAL: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  ON_SHIPMENT_FORM_FIELD_CHANGE: null,
  NEW_SHIPMENT: null,
  NEW_SHIPMENT_REQUEST: null,
  NEW_SHIPMENT_SUCCESS: null,
  NEW_SHIPMENT_FAILURE: null,

  GET_SHIPMENTS_REQUEST: null,
  GET_SHIPMENTS_SUCCESS: null,
  GET_SHIPMENTS_FAILURE: null,

  ON_SHIPMENT_SAVED: null

})
